# Generated by Django 3.1.1 on 2020-09-22 11:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiStDtbPoly',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('id_field', models.CharField(blank=True, db_column='id_', max_length=20, null=True)),
                ('dt_name', models.CharField(blank=True, max_length=40, null=True)),
                ('st_name', models.CharField(blank=True, max_length=40, null=True)),
                ('parts_field', models.IntegerField(blank=True, db_column='parts_', null=True)),
                ('points_field', models.IntegerField(blank=True, db_column='points_', null=True)),
                ('length_field', models.FloatField(blank=True, db_column='length_', null=True)),
                ('area_field', models.FloatField(blank=True, db_column='area_', null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'ni_st_dtb_poly',
                'managed': False,
            },
        ),
    ]
